name: OWASP Dependency Check

on:
  schedule:
    - cron: '30 6 * * FRI'

jobs:
  dependency-check:
    name: Analyze with OWASP Dependency Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v3.0.1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Run OWASP Dependency Check
        run: >
          mvn -B
          clean
          org.owasp:dependency-check-maven:aggregate

      - uses: actions/upload-artifact@v2
        with:
          name: dependency-check-report
          path: target/dependency-check-report.html

  dependency-check-build:
    name: Analyze with OWASP Dependency Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v3.0.1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Run OWASP Dependency Check
        run: >
          mvn -B
          clean
          org.owasp:dependency-check-maven:aggregate
          -DfailBuildOnAnyVulnerability=true
