# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: Maven Build

on:
  push:
  pull_request:

jobs:
  build:
    name: Build with JDK ${{ matrix.java }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [11, 14]
    steps:
      - uses: actions/checkout@v2.3.1

      - uses: actions/cache@v2.1.4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v2.2.0
        with:
          java-version: ${{ matrix.java }}

      - name: Build with Maven
        run: mvn -B package --file pom.xml

  sonar:
    name: Analysis with Sonar on JDK 11
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting for Sonar
          fetch-depth: 0

      - uses: actions/cache@v2.1.4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up JDK 11
        uses: actions/setup-java@v2.2.0
        with:
          java-version: 11

      - name: Analyze with SonarCloud
        run: >
          mvn -B
          clean verify sonar:sonar
          -Dsonar.projectKey=opencore_gdpdu-java
          -Dsonar.organization=opencore
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.login=$SONAR_TOKEN
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
